# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84065525f48e408b66907d6b8d98c2ab"
name = "Duc NH App Store"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# scopes = "write_products,write_metaobjects,write_metaobject_definitions"
scopes = "read_products,read_themes,read_customers,write_themes"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
